server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Rotas para Assinaturas
        - id: assinatura-service
          uri: lb://assinaturas
          predicates:
            - Path=/assinaturas/**
          filters:
            - name: CircuitBreaker
              args:
                name: assinaturaCircuitBreaker
                fallbackUri: forward:/fallback/assinaturas
            - RewritePath=/assinaturas/?(?<resto>.*), /$\{resto}

        # Rotas para Assinaturas
        - id: scaa-pas
          uri: lb://scaa-pas
          predicates:
            - Path=/scaa-pas/**
          filters:
            - name: CircuitBreaker
              args:
                name: scaaCircuitBreaker
                fallbackUri: forward:/fallback/scaa-pas
            - RewritePath=/scaa-pas/?(?<resto>.*), /$\{resto}

        # Rotas para Aplicativos
        - id: aplicativo-service
          uri: lb://aplicativo-service
          predicates:
            - Path=/aplicativos/**
          filters:
            - name: CircuitBreaker
              args:
                name: aplicativoCircuitBreaker
                fallbackUri: forward:/fallback/aplicativos
            - RewritePath=/aplicativos/?(?<resto>.*), /$\{resto}

        # Rotas para Clientes
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**
          filters:
            - name: CircuitBreaker
              args:
                name: clienteCircuitBreaker
                fallbackUri: forward:/fallback/clientes
            - RewritePath=/clientes/?(?<resto>.*), /$\{resto}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
